#!/bin/bash

#tile-monitor --pci --rtc --resume --here --mount-same ../reference --mount-tile /usr/lib --run --- time -p ../reference/lua "$@" --- --quit
#tile-monitor --pci --rtc --resume --here --mount-same ../reference --mount-tile /usr/lib --run --- ../reference/luac -l "$@" --- --quit
~/stdlua/lua5.1-5.1.4/src/luac -l "$@"
